#!/usr/bin/env python3
"""Generate only original geometric fixtures; never copy system/user fonts.

Fixture outlines and generator are licensed under this repository's GPL-3.0-only
license. These are diagnostic fonts, not readable typefaces for everyday use.
"""
import argparse
from pathlib import Path
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen


def generate(path, index):
    builder = FontBuilder(1000, isTTF=True)
    # The frozen composite engine counts distinct replaced glyphs, not cmap
    # aliases. Independent original ASCII outlines exercise real Latin/digit
    # replacement (>=52 letters and >=10 digits) instead of failing at preflight.
    ascii_glyphs = {c: f'ascii{c:04x}' for c in range(33, 127)}
    names = ['.notdef', 'space', 'shape', *ascii_glyphs.values()]
    builder.setupGlyphOrder(names)
    cmap = dict(ascii_glyphs)
    cmap.update({c: 'shape' for c in range(0x4E00, 0xA000)})
    cmap[32] = 'space'
    builder.setupCharacterMap(cmap)
    glyphs = {}
    for name in names:
        pen = TTGlyphPen(None)
        if name != 'space':
            pen.moveTo((100, 0))
            if index % 2:
                pen.lineTo((100, 700)); pen.lineTo((700, 700))
            else:
                pen.lineTo((400, 700))
            pen.lineTo((700, 0)); pen.closePath()
        glyphs[name] = pen.glyph()
    builder.setupGlyf(glyphs)
    builder.setupHorizontalMetrics({name: (800, 0) for name in names})
    builder.setupHorizontalHeader(ascent=800, descent=-200)
    builder.setupNameTable({'familyName': f'LuoShu Synthetic Gate {index:04d}',
        'styleName': 'Regular', 'uniqueFontIdentifier': f'luoshu-synthetic-{index:04d}',
        'fullName': f'LuoShu Synthetic Gate {index:04d} Regular',
        'psName': f'LuoShuSyntheticGate{index:04d}-Regular',
        'copyright': 'Original generated geometric fixture; GPL-3.0-only'})
    builder.setupOS2(sTypoAscender=800, sTypoDescender=-200,
                    usWinAscent=800, usWinDescent=200, usWeightClass=400)
    builder.setupPost(); builder.setupMaxp()
    builder.save(path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--count', required=True, type=int, choices=(2, 100, 1000))
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    for index in range(args.count):
        generate(args.output / f'LuoShuSyntheticGate{index:04d}.ttf', index)
    (args.output / 'LICENSE.txt').write_text('Original geometric test outlines generated by LuoShu.\nGPL-3.0-only; see repository LICENSE.\nNo system, user, commercial, or downloaded font outlines.\n')


if __name__ == '__main__':
    main()
