#!/system/bin/sh
# LuoShu persistent per-device alignment cache.
# A cache worker is preparation-only: it may create immutable aligned output, but it must never
# replace the active payload or request another reboot. Only an explicit foreground apply may
# activate a ready cache inside the caller's outer transaction.
set +e

_dfcache_module() {
    printf '%s\n' "${MODULE_DIR:-${MODDIR:-/data/adb/modules/LuoShu}}"
}

_dfcache_payload_root() {
    _dfc_module="$(_dfcache_module)"
    if type _lfrp_payload_root >/dev/null 2>&1; then
        _lfrp_payload_root
    elif [ -d "$_dfc_module/.luoshu-payload" ]; then
        printf '%s/.luoshu-payload\n' "${_dfc_module%/}"
    else
        printf '%s\n' "${_dfc_module%/}"
    fi
}

_dfcache_log() {
    _dfc_module="$(_dfcache_module)"
    mkdir -p "$_dfc_module/logs" 2>/dev/null || true
    printf '[%s] [CACHE] %s\n' "$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null || echo unknown)" "$*" \
        >> "$_dfc_module/logs/device-font-cache.log" 2>/dev/null || true
}

_dfcache_hash_stream() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | awk '{print $1}'
    elif command -v busybox >/dev/null 2>&1; then
        busybox sha256sum | awk '{print $1}'
    else
        cksum | awk '{print $1 ":" $2}'
    fi
}

_dfcache_template_key() {
    _dfc_module="$(_dfcache_module)"
    _dfc_template="$_dfc_module/common/device_font_template.sh"
    [ -f "$_dfc_template" ] || return 1
    MODDIR="$_dfc_module" sh "$_dfc_template" trusted >/dev/null 2>&1 || return 1
    _dfc_key=$(cat "$_dfc_module/config/device-font-template.key" 2>/dev/null)
    [ -n "$_dfc_key" ] || return 1
    printf '%s\n' "$_dfc_key"
}

# Metadata is only a memoization hint. The cache identity itself is built from font bytes, so
# reinstalling/updating the module or recreating a hard link cannot turn the same font into a miss.
_dfcache_source_identity() {
    _dfc_file="$1"
    if command -v stat >/dev/null 2>&1; then
        stat -c '%d:%i:%s:%y:%z' "$_dfc_file" 2>/dev/null && return 0
    fi
    if command -v toybox >/dev/null 2>&1; then
        toybox stat -c '%d:%i:%s:%y:%z' "$_dfc_file" 2>/dev/null && return 0
    fi
    return 1
}

_dfcache_file_digest() {
    _dfc_file="$1"
    _dfc_module="$(_dfcache_module)"
    _dfc_memo="$_dfc_module/config/device-font-source-digests.conf"
    _dfc_identity=$(_dfcache_source_identity "$_dfc_file" 2>/dev/null)
    if [ -n "$_dfc_identity" ] && [ -f "$_dfc_memo" ]; then
        _dfc_hit=$(awk -F'\t' -v k="$_dfc_identity" '$1 == k { print $2; exit }' "$_dfc_memo" 2>/dev/null)
        if [ -n "$_dfc_hit" ]; then
            printf '%s\n' "$_dfc_hit"
            return 0
        fi
    fi
    if command -v sha256sum >/dev/null 2>&1; then
        _dfc_digest=$(sha256sum "$_dfc_file" 2>/dev/null | awk '{print $1}')
    elif command -v busybox >/dev/null 2>&1; then
        _dfc_digest=$(busybox sha256sum "$_dfc_file" 2>/dev/null | awk '{print $1}')
    else
        _dfc_digest=$(cksum "$_dfc_file" 2>/dev/null | awk '{print $1 ":" $2}')
    fi
    [ -n "$_dfc_digest" ] || return 1
    if [ -n "$_dfc_identity" ]; then
        mkdir -p "${_dfc_memo%/*}" 2>/dev/null || true
        printf '%s\t%s\n' "$_dfc_identity" "$_dfc_digest" >> "$_dfc_memo" 2>/dev/null || true
    fi
    printf '%s\n' "$_dfc_digest"
}

_dfcache_source_key() {
    _dfc_module="$(_dfcache_module)"
    _dfc_store="$(_dfcache_payload_root)/system/fonts/.luoshu-font-store"
    [ -d "$_dfc_store" ] || return 1
    _dfc_files=$(find "$_dfc_store" -maxdepth 1 -type f -name '*.font' -print 2>/dev/null | LC_ALL=C sort)
    [ -n "$_dfc_files" ] || return 1
    {
        printf 'source-contract-v5-content\n'
        while IFS= read -r _dfc_file; do
            [ -f "$_dfc_file" ] || continue
            _dfc_digest=$(_dfcache_file_digest "$_dfc_file") || exit 1
            printf '%s|%s\n' "${_dfc_file##*/}" "$_dfc_digest"
        done <<EOF_DFCACHE_FILES
$_dfc_files
EOF_DFCACHE_FILES
    } | _dfcache_hash_stream
}

_dfcache_id() {
    _dfc_font="$1"
    _dfc_template_key="$2"
    _dfc_source_key="$3"
    printf 'alignment-cache-v5-content|%s|%s|%s\n' "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key" | _dfcache_hash_stream
}

# Read compatibility for caches generated by the v4 test builds. The live module path is stable
# after installation, so a preserved v4 cache can be proved with its original metadata contract
# once and promoted to the content-addressed contract without rebuilding FontTools output.
_dfcache_source_key_v4() {
    _dfc_store="$(_dfcache_payload_root)/system/fonts/.luoshu-font-store"
    [ -d "$_dfc_store" ] || return 1
    _dfc_files=$(find "$_dfc_store" -maxdepth 1 -type f -name '*.font' -print 2>/dev/null | LC_ALL=C sort)
    [ -n "$_dfc_files" ] || return 1
    {
        printf 'source-contract-v4\n'
        while IFS= read -r _dfc_file; do
            [ -f "$_dfc_file" ] || continue
            stat -c '%n|%d|%i|%s|%Y' "$_dfc_file" 2>/dev/null || ls -ln "$_dfc_file" 2>/dev/null
        done <<EOF_DFCACHE_V4_FILES
$_dfc_files
EOF_DFCACHE_V4_FILES
    } | _dfcache_hash_stream
}

_dfcache_id_v4() {
    printf 'alignment-cache-v4|%s|%s|%s\n' "$1" "$2" "$3" | _dfcache_hash_stream
}

_dfcache_copy_tree() {
    mkdir -p "$2" 2>/dev/null || return 1
    cp -al "$1/." "$2/" 2>/dev/null || \
        cp -af "$1/." "$2/" 2>/dev/null || \
        cp -rfp "$1/." "$2/" 2>/dev/null
}

_dfcache_root_for() {
    _dfc_font="$1"
    _dfc_template_key="$2"
    _dfc_source_key="$3"
    _dfc_id=$(_dfcache_id "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key") || return 1
    printf '%s/config/device-font-cache/%s\n' "$(_dfcache_module)" "$_dfc_id"
}

_dfcache_ready_matches() {
    _dfcrm_root="$1"
    _dfcrm_font="$2"
    _dfcrm_template_key="$3"
    _dfcrm_source_key="$4"
    _dfcrm_conf="$_dfcrm_root/cache.conf"
    [ -s "$_dfcrm_conf" ] && [ -s "$_dfcrm_root/payload/manifest.json" ] && [ -s "$_dfcrm_root/overlay/overlay-manifest.json" ] || return 1
    [ "$(sed -n 's/^state=//p' "$_dfcrm_conf" 2>/dev/null | head -n1)" = ready ] || return 1
    [ "$(sed -n 's/^font=//p' "$_dfcrm_conf" 2>/dev/null | head -n1)" = "$_dfcrm_font" ] || return 1
    [ "$(sed -n 's/^templateKey=//p' "$_dfcrm_conf" 2>/dev/null | head -n1)" = "$_dfcrm_template_key" ] || return 1
    [ "$(sed -n 's/^sourceKey=//p' "$_dfcrm_conf" 2>/dev/null | head -n1)" = "$_dfcrm_source_key" ] || return 1
    return 0
}

_dfcache_resolve_ready_root() {
    _dfc_font="$1"
    _dfc_template_key="$2"
    _dfc_source_key="$3"
    _dfc_module="$(_dfcache_module)"
    _dfc_new_id=$(_dfcache_id "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key") || return 2
    _dfc_new_root="$_dfc_module/config/device-font-cache/$_dfc_new_id"
    if _dfcache_ready_matches "$_dfc_new_root" "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key"; then
        printf '%s\n' "$_dfc_new_root"
        return 0
    fi

    _dfc_v4_source=$(_dfcache_source_key_v4) || return 2
    _dfc_v4_id=$(_dfcache_id_v4 "$_dfc_font" "$_dfc_template_key" "$_dfc_v4_source") || return 2
    _dfc_v4_root="$_dfc_module/config/device-font-cache/$_dfc_v4_id"
    _dfcache_ready_matches "$_dfc_v4_root" "$_dfc_font" "$_dfc_template_key" "$_dfc_v4_source" || return 2

    _dfc_stage="${_dfc_new_root}.promote.$$"
    rm -rf "$_dfc_stage" 2>/dev/null || true
    _dfcache_copy_tree "$_dfc_v4_root" "$_dfc_stage" || return 2
    sed -i "s/^cacheId=.*/cacheId=$_dfc_new_id/; s/^sourceKey=.*/sourceKey=$_dfc_source_key/" \
        "$_dfc_stage/cache.conf" 2>/dev/null || { rm -rf "$_dfc_stage" 2>/dev/null; return 2; }
    rm -rf "$_dfc_new_root" 2>/dev/null || { rm -rf "$_dfc_stage" 2>/dev/null; return 2; }
    mv -f "$_dfc_stage" "$_dfc_new_root" 2>/dev/null || { rm -rf "$_dfc_stage" 2>/dev/null; return 2; }
    _dfcache_ready_matches "$_dfc_new_root" "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key" || return 2
    _dfcache_log "已将 v4 设备对齐缓存迁移为内容键：$_dfc_font"
    printf '%s\n' "$_dfc_new_root"
}

device_font_cache_lookup() {
    _dfc_font="${1:-custom}"
    _dfc_template_key=$(_dfcache_template_key) || return 2
    _dfc_source_key=$(_dfcache_source_key) || return 2
    _dfcache_resolve_ready_root "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key" || return 2
    return 0
}

_dfcache_foreground_idle() {
    _dfc_module="$(_dfcache_module)"
    if type luoshu_font_lock_busy >/dev/null 2>&1; then
        luoshu_font_lock_busy "$_dfc_module/.font_switch.lock" && return 1
    else
        [ ! -e "$_dfc_module/.font_switch.lock" ] || return 1
    fi
    [ ! -e "$_dfc_module/.mount_compat.lock" ] || return 1
    if find "$_dfc_module/config" -maxdepth 1 -type d -name '.payload-transaction.*' -print -quit 2>/dev/null | grep -q .; then
        return 1
    fi
    return 0
}

# The aligned cache is a pure enhancement: fonts are already live through the physical slot mapping
# before it ever runs. It had no failure counter and no ceiling, and the pending marker was only
# removed on the success path, so a build that could never succeed on a given ROM was relaunched at
# full CPU on every single boot. That is how a font module ends up looking like a permanent load.
LUOSHU_CACHE_FAILURE_LIMIT="${LUOSHU_CACHE_FAILURE_LIMIT:-3}"
case "$LUOSHU_CACHE_FAILURE_LIMIT" in ''|*[!0-9]*) LUOSHU_CACHE_FAILURE_LIMIT=3 ;; esac
[ "$LUOSHU_CACHE_FAILURE_LIMIT" -ge 1 ] 2>/dev/null || LUOSHU_CACHE_FAILURE_LIMIT=1

_dfcache_failure_file() {
    printf '%s/config/device-font-cache-failures.conf\n' "$(_dfcache_module)"
}

_dfcache_failure_count() {
    _dfcf_value=$(sed -n 's/^count=//p' "$(_dfcache_failure_file)" 2>/dev/null | head -n1)
    case "$_dfcf_value" in ''|*[!0-9]*) _dfcf_value=0 ;; esac
    printf '%s\n' "$_dfcf_value"
}

_dfcache_failure_reset() {
    rm -f "$(_dfcache_failure_file)" 2>/dev/null || true
}

_dfcache_failure_record() {
    _dfcr_reason="${1:-unknown}"
    _dfcr_count=$(_dfcache_failure_count)
    _dfcr_count=$((_dfcr_count + 1))
    {
        printf 'count=%s\n' "$_dfcr_count"
        printf 'reason=%s\n' "$_dfcr_reason"
        printf 'time=%s\n' "$(date +%s 2>/dev/null || echo 0)"
    } > "$(_dfcache_failure_file)" 2>/dev/null || true
    if [ "$_dfcr_count" -ge "$LUOSHU_CACHE_FAILURE_LIMIT" ]; then
        rm -f "$(_dfcache_module)/config/device-font-cache-pending.conf" 2>/dev/null || true
        _dfcache_log "设备对齐缓存连续失败 ${_dfcr_count} 次，已放弃并停止重试（reason=${_dfcr_reason}）；字体本身已由物理槽映射生效，此项仅为增强"
    else
        _dfcache_log "设备对齐缓存失败 ${_dfcr_count}/${LUOSHU_CACHE_FAILURE_LIMIT}（reason=${_dfcr_reason}）"
    fi
}

# Both launchers must run the builder at the lowest priority available. One of them did not, so
# whether the heavy fontTools pass competed with the UI depended on which path happened to start it.
_dfcache_run_service_lowpri() {
    _dfcrs_module="$1"
    MODDIR="$_dfcrs_module"
    MODULE_DIR="$_dfcrs_module"
    export MODDIR MODULE_DIR
    mkdir -p "$_dfcrs_module/logs" 2>/dev/null || true
    if command -v ionice >/dev/null 2>&1 && command -v nice >/dev/null 2>&1; then
        ionice -c 3 nice -n 19 sh "$_dfcrs_module/common/device_font_cache.sh" service \
            >> "$_dfcrs_module/logs/device-font-cache.log" 2>&1
    elif command -v nice >/dev/null 2>&1; then
        nice -n 19 sh "$_dfcrs_module/common/device_font_cache.sh" service \
            >> "$_dfcrs_module/logs/device-font-cache.log" 2>&1
    else
        sh "$_dfcrs_module/common/device_font_cache.sh" service \
            >> "$_dfcrs_module/logs/device-font-cache.log" 2>&1
    fi
}

# Cache locks survive in the persistent module directory, so a reboot/OOM can leave one behind.
# Reuse the font-switch identity lock helpers (PID + starttime + boot_id) when available; this
# avoids treating a recycled PID after reboot as the old cache worker.
_dfcache_load_lock_helpers() {
    type luoshu_font_lock_acquire >/dev/null 2>&1 &&
        type luoshu_font_lock_reap_stale >/dev/null 2>&1 &&
        type luoshu_font_lock_release >/dev/null 2>&1 && return 0
    _dfcl_module="$(_dfcache_module)"
    _dfcl_util="$_dfcl_module/common/util_functions.sh"
    [ -f "$_dfcl_util" ] && . "$_dfcl_util"
    type luoshu_font_lock_acquire >/dev/null 2>&1 &&
        type luoshu_font_lock_reap_stale >/dev/null 2>&1 &&
        type luoshu_font_lock_release >/dev/null 2>&1
}

_dfcache_lock_reap_stale() {
    _dfclr_lock="$1"
    [ -e "$_dfclr_lock" ] || return 0
    if _dfcache_load_lock_helpers; then
        luoshu_font_lock_active "$_dfclr_lock" >/dev/null 2>&1 && return 1
        luoshu_font_lock_reap_stale "$_dfclr_lock" >/dev/null 2>&1 || true
        [ ! -e "$_dfclr_lock" ]
        return $?
    fi
    # Minimal fallback for stripped/test environments where util_functions.sh is unavailable.
    _dfclr_owner=$(sed -n '1p' "$_dfclr_lock/pid" 2>/dev/null)
    case "$_dfclr_owner" in
        ''|*[!0-9]*)
            sleep 1 2>/dev/null || true
            _dfclr_owner=$(sed -n '1p' "$_dfclr_lock/pid" 2>/dev/null)
            ;;
    esac
    case "$_dfclr_owner" in
        ''|*[!0-9]*) ;;
        *) kill -0 "$_dfclr_owner" 2>/dev/null && return 1 ;;
    esac
    rm -f "$_dfclr_lock/pid" 2>/dev/null || true
    rmdir "$_dfclr_lock" 2>/dev/null || true
    [ ! -e "$_dfclr_lock" ]
}

_dfcache_lock_acquire() {
    _dfcla_lock="$1"
    if _dfcache_load_lock_helpers; then
        luoshu_font_lock_acquire "$_dfcla_lock" "$$"
        return $?
    fi
    _dfcache_lock_reap_stale "$_dfcla_lock" >/dev/null 2>&1 || {
        [ ! -e "$_dfcla_lock" ] || return 2
    }
    mkdir "$_dfcla_lock" 2>/dev/null || return 2
    printf '%s\n' "$$" > "$_dfcla_lock/pid" 2>/dev/null || {
        rmdir "$_dfcla_lock" 2>/dev/null || true
        return 1
    }
    return 0
}

_dfcache_lock_release() {
    _dfclx_lock="$1"
    if _dfcache_load_lock_helpers; then
        luoshu_font_lock_release "$_dfclx_lock" "$$" >/dev/null 2>&1 && return 0
    fi
    _dfclx_owner=$(sed -n '1p' "$_dfclx_lock/pid" 2>/dev/null)
    [ -z "$_dfclx_owner" ] || [ "$_dfclx_owner" = "$$" ] || return 1
    rm -f "$_dfclx_lock/pid" 2>/dev/null || true
    rmdir "$_dfclx_lock" 2>/dev/null || true
    [ ! -e "$_dfclx_lock" ]
}

_dfcache_autostart_pending() {
    _dfc_font="$1"
    _dfc_module="$(_dfcache_module)"
    _dfc_script="$_dfc_module/common/device_font_cache.sh"
    [ "${LUOSHU_CACHE_AUTOSTART:-1}" != 0 ] || return 0
    [ -f "$_dfc_script" ] || return 0
    (
        _dfc_waited=0
        _dfc_active=''
        while [ "$_dfc_waited" -lt 120 ]; do
            _dfc_active=$(head -n1 "$_dfc_module/config/active_font.conf" 2>/dev/null | tr -d '\r\n')
            _dfc_pending_font=$(sed -n 's/^font=//p' "$_dfc_module/config/device-font-cache-pending.conf" 2>/dev/null | head -n1)
            if [ "$_dfc_active" = "$_dfc_font" ] && [ "$_dfc_pending_font" = "$_dfc_font" ] && _dfcache_foreground_idle; then
                break
            fi
            sleep 1
            _dfc_waited=$((_dfc_waited + 1))
        done
        [ "$_dfc_active" = "$_dfc_font" ] && [ "$_dfc_pending_font" = "$_dfc_font" ] && _dfcache_foreground_idle || exit 0
        sleep 2
        _dfcache_foreground_idle || exit 0
        MODDIR="$_dfc_module"
        MODULE_DIR="$_dfc_module"
        export MODDIR MODULE_DIR
        _dfcache_run_service_lowpri "$_dfc_module"
    ) &
    return 0
}

device_font_cache_schedule() {
    _dfc_font="${1:-custom}"
    _dfc_module="$(_dfcache_module)"
    _dfc_pending="$_dfc_module/config/device-font-cache-pending.conf"
    _dfc_template_key=$(_dfcache_template_key) || {
        _dfcache_log '无法安排对齐缓存：可信原厂模板尚未建立'
        return 2
    }
    _dfc_source_key=$(_dfcache_source_key) || {
        _dfcache_log '无法安排对齐缓存：当前字体源锚点不存在'
        return 2
    }
    _dfc_id=$(_dfcache_id "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key") || return 1
    mkdir -p "$_dfc_module/config" 2>/dev/null || return 1
    {
        printf 'state=pending\n'
        printf 'font=%s\n' "$_dfc_font"
        printf 'cacheId=%s\n' "$_dfc_id"
        printf 'templateKey=%s\n' "$_dfc_template_key"
        printf 'sourceKey=%s\n' "$_dfc_source_key"
        printf 'time=%s\n' "$(date +%s 2>/dev/null || echo 0)"
    } > "${_dfc_pending}.tmp.$$" 2>/dev/null || return 1
    mv -f "${_dfc_pending}.tmp.$$" "$_dfc_pending" 2>/dev/null || return 1
    chmod 0600 "$_dfc_pending" 2>/dev/null || true
    # An explicit switch is a new intent, not a retry of the thing that kept failing.
    _dfcache_failure_reset
    _dfcache_log "已安排后台生成设备对齐缓存：$_dfc_font"
    _dfcache_autostart_pending "$_dfc_font"
    return 0
}

_dfcache_write_engine_state() {
    _dfc_font="$1"
    _dfc_template_key="$2"
    _dfc_source_key="$3"
    _dfc_cache_id="$4"
    _dfc_module="$(_dfcache_module)"
    _dfc_state="$_dfc_module/config/device-font-engine.conf"
    {
        printf 'state=installed\n'
        printf 'schema=device-font-payload-v2\n'
        printf 'font=%s\n' "$_dfc_font"
        printf 'templateKey=%s\n' "$_dfc_template_key"
        printf 'sourceKey=%s\n' "$_dfc_source_key"
        printf 'cacheId=%s\n' "$_dfc_cache_id"
        printf 'planRevision=2\n'
        printf 'time=%s\n' "$(date +%s 2>/dev/null || echo 0)"
    } > "${_dfc_state}.tmp.$$" 2>/dev/null || return 1
    mv -f "${_dfc_state}.tmp.$$" "$_dfc_state" 2>/dev/null || return 1
    chmod 0600 "$_dfc_state" 2>/dev/null || true
}

device_font_cache_activate() {
    _dfc_font="${1:-custom}"
    _dfc_module="$(_dfcache_module)"
    _dfc_template_key=$(_dfcache_template_key) || return 2
    _dfc_source_key=$(_dfcache_source_key) || return 2
    _dfc_root=$(_dfcache_resolve_ready_root "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key") || return 2
    _dfc_cache_id=${_dfc_root##*/}
    type _dfpr_install_overlay >/dev/null 2>&1 || return 1
    _dfpr_install_overlay "$_dfc_root/overlay" || return 1
    _dfcache_write_engine_state "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key" "$_dfc_cache_id" || return 1
    # _dfpr_install_overlay already verifies every copied target and records its exact digest.
    # Re-reading every multi-megabyte font immediately afterward doubled activation time.
    rm -f "$_dfc_module/config/device-font-cache-pending.conf" 2>/dev/null || true
    _dfcache_log "设备对齐缓存已激活：$_dfc_font cache=$_dfc_cache_id"
    return 0
}

_dfcache_runtime_ready() {
    _dfc_module="$(_dfcache_module)"
    if ! type _dfpr_exec >/dev/null 2>&1 || ! type _dfpr_prepare_sources >/dev/null 2>&1 || ! type _dfpr_install_overlay >/dev/null 2>&1; then
        [ -f "$_dfc_module/common/device_font_payload_runtime.sh" ] || return 1
        . "$_dfc_module/common/device_font_payload_runtime.sh"
    fi
    # Preparation writes only an immutable cache directory. It deliberately does not load the
    # payload transaction or mount stack; those belong exclusively to explicit activation.
    type _dfpr_exec >/dev/null 2>&1 &&
        type _dfpr_prepare_sources >/dev/null 2>&1
}

_dfcache_notify() {
    _dfc_message="$1"
    command -v cmd >/dev/null 2>&1 || return 0
    cmd notification post -S bigtext -t '洛书' luoshu-font-cache "$_dfc_message" >/dev/null 2>&1 || \
        cmd notification post -t '洛书' luoshu-font-cache "$_dfc_message" >/dev/null 2>&1 || true
}

_dfcache_prune() {
    _dfc_keep="$1"
    _dfc_module="$(_dfcache_module)"
    _dfc_base="$_dfc_module/config/device-font-cache"
    [ -d "$_dfc_base" ] || return 0
    _dfc_seen=0
    for _dfc_dir in $(ls -1dt "$_dfc_base"/* 2>/dev/null); do
        [ -d "$_dfc_dir" ] || continue
        [ "$_dfc_dir" = "$_dfc_keep" ] && continue
        _dfc_seen=$((_dfc_seen + 1))
        [ "$_dfc_seen" -le 1 ] || rm -rf "$_dfc_dir" 2>/dev/null || true
    done
}

_dfcache_build_pending_inner() {
    _dfc_module="$(_dfcache_module)"
    _dfc_pending="$_dfc_module/config/device-font-cache-pending.conf"
    _dfc_lock="$_dfc_module/.device-font-cache.lock"
    [ -s "$_dfc_pending" ] || return 2
    [ "${LUOSHU_CACHE_FOREGROUND:-0}" = 1 ] || _dfcache_foreground_idle || {
        _dfcache_log '前台字体事务尚未结束，后台缓存本轮跳过并保留待办'
        return 2
    }
    # Isolate the worker's EXIT trap. device_font_cache.sh is also sourced by font_manager.sh;
    # installing a trap in that parent shell used to erase the outer rollback handler.
    (
    _dfcache_lock_acquire "$_dfc_lock"
    _dfc_lock_rc=$?
    case "$_dfc_lock_rc" in
        0) ;;
        2) _dfcache_log '后台对齐缓存任务已经在运行'; return 2 ;;
        *) _dfcache_log '后台对齐缓存锁创建失败'; return 1 ;;
    esac
    trap '_dfcache_lock_release "$_dfc_lock" >/dev/null 2>&1 || true' EXIT HUP INT TERM

    _dfc_font=$(sed -n 's/^font=//p' "$_dfc_pending" 2>/dev/null | head -n1)
    _dfc_cache_id=$(sed -n 's/^cacheId=//p' "$_dfc_pending" 2>/dev/null | head -n1)
    _dfc_expected_template=$(sed -n 's/^templateKey=//p' "$_dfc_pending" 2>/dev/null | head -n1)
    _dfc_expected_source=$(sed -n 's/^sourceKey=//p' "$_dfc_pending" 2>/dev/null | head -n1)
    _dfc_active=$(head -n1 "$_dfc_module/config/active_font.conf" 2>/dev/null | tr -d '\r\n')
    [ -n "$_dfc_font" ] && [ "$_dfc_font" != default ] && \
        { [ "${LUOSHU_CACHE_FOREGROUND:-0}" = 1 ] || [ "$_dfc_active" = "$_dfc_font" ]; } || {
        _dfcache_log "取消过期缓存任务：pending=$_dfc_font active=$_dfc_active"
        rm -f "$_dfc_pending" 2>/dev/null || true
        return 2
    }
    _dfc_template_key=$(_dfcache_template_key) || return 2
    _dfc_source_key=$(_dfcache_source_key) || return 2
    [ "$_dfc_template_key" = "$_dfc_expected_template" ] && [ "$_dfc_source_key" = "$_dfc_expected_source" ] || {
        _dfcache_log '缓存任务源指纹已经变化，等待下次明确应用重新安排'
        rm -f "$_dfc_pending" 2>/dev/null || true
        return 2
    }
    _dfc_root="$_dfc_module/config/device-font-cache/$_dfc_cache_id"
    if _dfcache_ready_matches "$_dfc_root" "$_dfc_font" "$_dfc_template_key" "$_dfc_source_key"; then
        _dfcache_log "后台缓存已经存在：$_dfc_font"
    else
        _dfcache_runtime_ready || return 1
        _dfpr_prepare_sources || {
            _dfcache_log '后台缓存无法准备九档源锚点'
            return 1
        }
        _dfc_stage="$_dfc_module/config/device-font-cache/.stage.${_dfc_cache_id}.$$"
        rm -rf "$_dfc_stage" 2>/dev/null || true
        mkdir -p "$_dfc_stage" 2>/dev/null || return 1
        _dfc_build="$_dfc_module/common/device_font_payload_build.py"
        _dfc_render="$_dfc_module/common/device_font_payload_overlay.py"
        _dfc_verify="$_dfc_module/common/device_font_payload_verify.py"
        _dfc_template="$_dfc_module/config/device-font-template.json"
        _dfc_build_result=$(_dfpr_exec "$_dfc_build" \
            --template "$_dfc_template" \
            --source-dir "$_dfc_module/config/device-font-sources" \
            --source-prefix LuoShu \
            --output-dir "$_dfc_stage/payload" \
            --manifest "$_dfc_stage/payload/manifest.json" 2>> "$_dfc_module/logs/device-font-cache.log")
        _dfc_rc=$?
        if [ "$_dfc_rc" -ne 0 ] || [ ! -s "$_dfc_stage/payload/manifest.json" ]; then
            rm -rf "$_dfc_stage" 2>/dev/null || true
            _dfcache_log "后台生成设备对齐字体失败：$_dfc_build_result"
            return 1
        fi
        _dfc_verify_result=$(_dfpr_exec "$_dfc_verify" --manifest "$_dfc_stage/payload/manifest.json" --root "$_dfc_stage/payload" 2>> "$_dfc_module/logs/device-font-cache.log")
        [ $? -eq 0 ] || {
            rm -rf "$_dfc_stage" 2>/dev/null || true
            _dfcache_log "后台字体负载验证失败：$_dfc_verify_result"
            return 1
        }
        _dfc_overlay_result=$(_dfpr_exec "$_dfc_render" \
            --template "$_dfc_template" \
            --payload "$_dfc_stage/payload/manifest.json" \
            --payload-root "$_dfc_stage/payload" \
            --output-tree "$_dfc_stage/overlay" 2>> "$_dfc_module/logs/device-font-cache.log")
        if [ $? -ne 0 ] || [ ! -s "$_dfc_stage/overlay/overlay-manifest.json" ]; then
            rm -rf "$_dfc_stage" 2>/dev/null || true
            _dfcache_log "后台设备字体映射失败：$_dfc_overlay_result"
            return 1
        fi
        {
            printf 'state=ready\n'
            printf 'font=%s\n' "$_dfc_font"
            printf 'cacheId=%s\n' "$_dfc_cache_id"
            printf 'templateKey=%s\n' "$_dfc_template_key"
            printf 'sourceKey=%s\n' "$_dfc_source_key"
            printf 'engine=script-anchor-v2\n'
            printf 'time=%s\n' "$(date +%s 2>/dev/null || echo 0)"
        } > "$_dfc_stage/cache.conf" 2>/dev/null || {
            rm -rf "$_dfc_stage" 2>/dev/null || true
            return 1
        }
        mkdir -p "${_dfc_root%/*}" 2>/dev/null || return 1
        rm -rf "${_dfc_root}.previous" 2>/dev/null || true
        [ ! -d "$_dfc_root" ] || mv "$_dfc_root" "${_dfc_root}.previous" 2>/dev/null || return 1
        if mv "$_dfc_stage" "$_dfc_root" 2>/dev/null; then
            rm -rf "${_dfc_root}.previous" 2>/dev/null || true
        else
            [ ! -d "${_dfc_root}.previous" ] || mv "${_dfc_root}.previous" "$_dfc_root" 2>/dev/null || true
            rm -rf "$_dfc_stage" 2>/dev/null || true
            return 1
        fi
        _dfcache_log "后台设备对齐缓存生成完成：font=$_dfc_font verify=$_dfc_verify_result"
    fi

    [ "${LUOSHU_CACHE_FOREGROUND:-0}" = 1 ] || _dfcache_foreground_idle || {
        _dfcache_log '缓存已生成；前台事务正在运行，本轮只保留就绪缓存'
    }
    # Re-read intent after the expensive build. A stale worker may finish its immutable cache, but
    # it can never publish state over a newer explicit switch.
    _dfc_live_font=$(sed -n 's/^font=//p' "$_dfc_pending" 2>/dev/null | head -n1)
    _dfc_live_id=$(sed -n 's/^cacheId=//p' "$_dfc_pending" 2>/dev/null | head -n1)
    if [ "$_dfc_live_font" != "$_dfc_font" ] || [ "$_dfc_live_id" != "$_dfc_cache_id" ]; then
        _dfcache_log "缓存任务已被新的显式切换取消，不激活旧负载：$_dfc_font"
        return 2
    fi
    rm -f "$_dfc_pending" 2>/dev/null || true
    _dfcache_prune "$_dfc_root"
    if [ "${LUOSHU_CACHE_FOREGROUND:-0}" != 1 ]; then
        _dfcache_notify '设备对齐字体缓存已准备完成；下次明确应用该字体时会一次提交。'
    fi
    _dfcache_log "设备对齐缓存已就绪且未改动当前字体：$_dfc_font"
    _dfcache_lock_release "$_dfc_lock" >/dev/null 2>&1 || true
    trap - EXIT HUP INT TERM
    return 0
    )
}

# rc=2 means "not now" (foreground busy, nothing pending, no template yet) and must not burn the
# failure budget. Only a real build or activation failure counts.
device_font_cache_build_pending() {
    _dfcache_build_pending_inner "$@"
    _dfcbp_rc=$?
    case "$_dfcbp_rc" in
        0) _dfcache_failure_reset ;;
        1) _dfcache_failure_record build ;;
    esac
    return "$_dfcbp_rc"
}

if [ "${0##*/}" = device_font_cache.sh ]; then
    case "${1:-service}" in
        service|build-pending) device_font_cache_build_pending ;;
        schedule) device_font_cache_schedule "${2:-custom}" ;;
        activate) device_font_cache_activate "${2:-custom}" ;;
        lookup) device_font_cache_lookup "${2:-custom}" ;;
        source-key) _dfcache_source_key ;;
        *) echo 'Usage: device_font_cache.sh {service|schedule FONT|activate FONT|lookup FONT|source-key}' >&2; exit 2 ;;
    esac
fi
