# Reproducible composite-runtime inputs. Update hashes and licenses in the same change.
LUOSHU_PY_VERSION=3.14.6
LUOSHU_PY_ARCHIVE=python-3.14.6-aarch64-linux-android.tar.gz
LUOSHU_PY_SHA256=38bbe77d3167b5cd554e03b1021324926f09f3825202b065951dd7638e9c37e5
LUOSHU_FONTTOOLS_VERSION=4.63.0
LUOSHU_ANDROID_NDK_VERSION=27.0.12077973
LUOSHU_ANDROID_MIN_API=26
