#!/usr/bin/env python3
"""Check the pinned 1.1.1 boot/mount core and the delivered task helpers."""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parents[1]
BASELINE = "be39f598bfb921526851c5c4a2e92905dacf4ea7"
HELPERS = (
    "common/task_scope.py", "common/task_scope.sh",
    "common/runtime_paths.sh", "common/runtime_paths_lock.py",
    "common/font_next_transaction.sh", "common/font_live_switch.sh", "common/font_live_payload.py",
)
REPOSITORY = "xgl34222220-ops/LuoShu"
UPDATE_CHANNELS = ("update.json", "update-prerelease.json")


def _key_values(path):
    values = {}
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            key, sep, value = line.partition("=")
            if sep and key.strip() not in values:
                values[key.strip()] = value.strip()
    return values


def official_release_metadata(root, name):
    """Return the exact bytes sync-update-metadata publishes for the release
    the owner authorized in module.prop, or None when no such release exists.

    After a signed stable release, the sync-update-metadata bot rewrites the
    update channels on main. That state is allowed only when every field is
    derived from the authorized release (same version/versionCode as
    module.prop, matching release tag and notes); any other edit still fails.
    """
    if name not in UPDATE_CHANNELS:
        return None
    prop = _key_values(root / "module.prop")
    auth = _key_values(root / "config/stable_release_authorization.conf")
    version, code = prop.get("version", ""), prop.get("versionCode", "")
    if not version or not code.isdigit() or int(code) <= 0:
        return None
    if auth.get("version") != version or auth.get("scope") != "stable-release":
        return None
    spec = importlib.util.spec_from_file_location(
        "_luoshu_sync_update_metadata", ROOT / "scripts/sync_update_metadata.py")
    sync = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sync)
    artifact = sync.artifact_version(version)
    series = prop.get("versionSeries", "")
    if series == "refactor":
        tag = f"refactor-{artifact}"
    elif series in ("", "legacy"):
        tag = artifact
    else:
        return None
    notes = f"RELEASE_NOTES_{tag}.md"
    if not (root / notes).is_file():
        return None
    meta = sync.build_metadata(repository=REPOSITORY, version=version,
                               version_code=int(code), tag=tag, notes_file=notes)
    return (json.dumps(meta, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def published_channel_allowed(root, name, pinned):
    data = (root / name).read_bytes()
    # The owner authorized only the 2.2.2 channel promotion. Pin its exact
    # generated bytes as an additional allowed state; the 22 runtime hashes
    # remain unchanged, and other channel edits still fail closed.
    promotion = pinned.get("authorizedPublishedMetadataSha256", {})
    authorized = promotion.get("sha256", {}) if promotion.get("version") == "v2.2.2" else {}
    actual = hashlib.sha256(data).hexdigest()
    if actual in (pinned["publishedMetadataSha256"][name], authorized.get(name)):
        return True
    return data == official_release_metadata(root, name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", type=Path)
    args = parser.parse_args()
    pinned = json.loads((ROOT / "scripts/stable111_frozen_runtime.json").read_text())
    assert pinned["baselineCommit"] == BASELINE, "unexpected baseline"
    assert len(pinned["sha256"]) == 22, "incomplete frozen runtime inventory"
    manifest = set((ROOT / "scripts/module_payload_manifest.txt").read_text().splitlines())
    for name in HELPERS:
        assert name in manifest and (ROOT / name).is_file(), f"missing helper: {name}"
    for name, digest in pinned["sha256"].items():
        assert hashlib.sha256((ROOT / name).read_bytes()).hexdigest() == digest, f"frozen core changed: {name}"
    for name in pinned["publishedMetadataSha256"]:
        assert published_channel_allowed(ROOT, name, pinned), f"published channel changed: {name}"
    assert not (ROOT / "common/luoshu_engine.py").exists(), "post-1.1.1 engine carried over"
    assert not (ROOT / "common/luoshu_engine.sh").exists(), "post-1.1.1 engine carried over"
    assert not (ROOT / "common/luoshu_engine_v3.py").exists(), "post-1.1.1 engine carried over"
    if args.zip:
        with zipfile.ZipFile(args.zip) as archive:
            assert archive.testzip() is None, "damaged ZIP"
            names = archive.namelist()
            assert len(names) == len(set(names)), "duplicate archive entries"
            for name in names:
                parts = Path(name).parts
                assert not name.startswith("/") and ".." not in parts, f"unsafe archive name: {name}"
                assert ".luoshu-state" not in parts and "__pycache__" not in parts, f"runtime residue packaged: {name}"
            for name in HELPERS:
                assert archive.read(name) == (ROOT / name).read_bytes(), f"wrong packaged helper: {name}"
            for name, digest in pinned["sha256"].items():
                assert hashlib.sha256(archive.read(name)).hexdigest() == digest, f"wrong packaged core: {name}"
    print("Pinned 1.1.1 core and task-helper payload checks passed.")


if __name__ == "__main__":
    main()
